sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t alp2003/docker-frontend-prod -f Dockerfile.dev .

script:
    - docker run -e CI=true alp2003/docker-frontend-prod npm run test

deploy:
    provider: elasticbeanstalk
    region: 'us-east-1'
    app: 'docker-react-dev'
    env: 'Dockerreactdev-env'
    bucket_name: 'elasticbeanstalk-us-east-1-931702435652'
    bucket_path: 'docker-react-dev'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
#dev
