FROM node:16-alpine

WORKDIR '/app'

COPY package.json .

# RUN npm config set unsafe-perm true
RUN npm install
# RUN chown -R node /usr/frontend/node_modules
# USER node


COPY . .


CMD ["npm", "start"]


# * override CMD with: docker exec -it frontend-app npm run test